import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoSerif = localFont({
  src: [
    {
      path: "../public/type/NotoSerifDisplay-VariableFont_wdth,wght.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-noto-serif",
  display: "swap",
});

const Oranienbaum = localFont({
  src: [
    {
      path: "../public/type/Oranienbaum-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-oranienbaum",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${notoSerif.variable} ${Oranienbaum.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
